name: deepan
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - expat=2.6.3
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.12.7
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024b
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - attrs==24.2.0
      - cffi==1.17.1
      - contourpy==1.3.0
      - cycler==0.12.1
      - flatbuffers==24.3.25
      - fonttools==4.54.1
      - grpcio==1.67.0
      - jax==0.4.34
      - jaxlib==0.4.34
      - jinja2==3.1.4
      - kiwisolver==1.4.7
      - markdown==3.7
      - markupsafe==3.0.1
      - matplotlib==3.9.2
      - mediapipe==0.10.15
      - ml-dtypes==0.5.0
      - opencv-contrib-python==4.10.0.84
      - opt-einsum==3.4.0
      - packaging==24.1
      - pillow==11.0.0
      - protobuf==4.25.5
      - pycparser==2.22
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - scipy==1.14.1
      - six==1.16.0
      - sounddevice==0.5.1
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - typing-extensions==4.12.2
      - werkzeug==3.0.4